server:
  servlet:
    context-path: /fastmomomer #
  port: 8888 # 端口

spring:
  profiles:
    active: dev

  web:
    resources:
      #不要为我们工程中的资源文件建立映射
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  #mysql数据源
  datasource:
    #数据源
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: bajiechifan2022
      # 初始化大小，最小，最大
      initial-size: 10
      max-active: 30
      min-idle: 5
      max-wait: 3000                                           # 获取数据库连接等待的超时时间
      max-open-prepared-statements: -1
      time-between-eviction-runs-millis: 60000                 # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      min-evictable-idle-time-millis: 300000                   # 配置连接在池中的最小生存时间
      max-evictable-idle-time-millis: 400000                   # 配置连接在池中的最大生存时间
      validation-query: SELECT 1                               #系统启动时通过该sql语句验证数据库是否可用，如果不配置validationQuery，则下面三项无效
      test-while-idle: true                                    #启用空闲连接检测，以便回收
      test-on-borrow: false                                    #从连接池获取连接时，是否检测连接可用性，开启性能会有些许影响
      test-on-return: false                                    #释放连接到连接池时，是否检测连接可用性，开启性能会有些许影响
      pool-prepared-statements: false                          #打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall                                       #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据

  #redis
  redis:
    database: 0  #Redis索引0~15，默认为0
    host: 127.0.0.1
    port: 6379
    password: aaaaa
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 300   #连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 50     #连接池中的最大空闲连接
        min-idle: 5     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）

logging:
  config: classpath:logback-spring.xml #日志配置文件


